/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BilletsRouteImport } from './routes/billets'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as CaravaneIdRouteImport } from './routes/caravane.$id'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as OrganizerDashboardRouteImport } from './routes/organizer.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BilletsRoute = BilletsRouteImport.update({
  id: '/billets',
  path: '/billets',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const CaravaneIdRoute = CaravaneIdRouteImport.update({
  id: '/caravane/$id',
  path: '/caravane/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerDashboardRoute = OrganizerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrganizerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billets': typeof BilletsRoute
  '/favoris': typeof FavorisRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/profil': typeof ProfilRoute
  '/caravane/$id': typeof CaravaneIdRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/': typeof OrganizerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billets': typeof BilletsRoute
  '/favoris': typeof FavorisRoute
  '/profil': typeof ProfilRoute
  '/caravane/$id': typeof CaravaneIdRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer': typeof OrganizerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billets': typeof BilletsRoute
  '/favoris': typeof FavorisRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/profil': typeof ProfilRoute
  '/caravane/$id': typeof CaravaneIdRoute
  '/organizer/dashboard': typeof OrganizerDashboardRoute
  '/organizer/': typeof OrganizerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billets'
    | '/favoris'
    | '/organizer'
    | '/profil'
    | '/caravane/$id'
    | '/organizer/dashboard'
    | '/organizer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billets'
    | '/favoris'
    | '/profil'
    | '/caravane/$id'
    | '/organizer/dashboard'
    | '/organizer'
  id:
    | '__root__'
    | '/'
    | '/billets'
    | '/favoris'
    | '/organizer'
    | '/profil'
    | '/caravane/$id'
    | '/organizer/dashboard'
    | '/organizer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilletsRoute: typeof BilletsRoute
  FavorisRoute: typeof FavorisRoute
  OrganizerRoute: typeof OrganizerRouteWithChildren
  ProfilRoute: typeof ProfilRoute
  CaravaneIdRoute: typeof CaravaneIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billets': {
      id: '/billets'
      path: '/billets'
      fullPath: '/billets'
      preLoaderRoute: typeof BilletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caravane/$id': {
      id: '/caravane/$id'
      path: '/caravane/$id'
      fullPath: '/caravane/$id'
      preLoaderRoute: typeof CaravaneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/dashboard': {
      id: '/organizer/dashboard'
      path: '/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof OrganizerDashboardRouteImport
      parentRoute: typeof OrganizerRoute
    }
  }
}

interface OrganizerRouteChildren {
  OrganizerDashboardRoute: typeof OrganizerDashboardRoute
  OrganizerIndexRoute: typeof OrganizerIndexRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerDashboardRoute: OrganizerDashboardRoute,
  OrganizerIndexRoute: OrganizerIndexRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilletsRoute: BilletsRoute,
  FavorisRoute: FavorisRoute,
  OrganizerRoute: OrganizerRouteWithChildren,
  ProfilRoute: ProfilRoute,
  CaravaneIdRoute: CaravaneIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
